# Generated by Django 4.1.7 on 2023-04-15 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blood_donate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloodrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('volume', models.IntegerField()),
                ('blood_group', models.CharField(max_length=3)),
                ('description', models.CharField(max_length=150)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='donator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('CCID', models.CharField(max_length=12)),
            ],
        ),
        migrations.DeleteModel(
            name='requester',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='Donators',
            field=models.ManyToManyField(to='blood_donate.donator'),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
