# Generated by Django 4.1.7 on 2023-04-15 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donate', '0003_alter_bloodrequest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='Donators',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='Donator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blood_donate.donator'),
        ),
    ]
