# Generated by Django 4.1.7 on 2023-04-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donate', '0004_remove_bloodrequest_donators_bloodrequest_donator'),
    ]

    operations = [
        migrations.AddField(
            model_name='donator',
            name='PhnNo',
            field=models.CharField(default=919191919191, max_length=13),
        ),
    ]
