# Generated by Django 4.1.7 on 2023-04-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood_donate', '0005_donator_phnno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donator',
            name='PhnNo',
            field=models.CharField(blank=True, default=919191919191, max_length=13),
        ),
    ]
