# Generated by Django 4.1.7 on 2023-03-19 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.CharField(choices=[('Department1', 'Department1'), ('Department2', 'Department2'), ('Department3', 'Department3'), ('Department4', 'Department4'), ('Department5', 'Department5')], max_length=120)),
                ('Doctor_Name', models.CharField(max_length=50, null=True)),
                ('Post', models.CharField(default='Nurse', max_length=60)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.account')),
            ],
        ),
        migrations.CreateModel(
            name='Time_Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.IntegerField(null=True)),
                ('total_patient', models.IntegerField(default=0)),
                ('date', models.DateField(null=True)),
                ('doctors', models.ManyToManyField(to='health.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_Name', models.CharField(max_length=600, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.account')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health.doctor')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health.patient')),
                ('timeSlot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health.time_slot')),
            ],
        ),
    ]
