# Generated by Django 4.1.7 on 2023-04-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Department',
            field=models.CharField(choices=[('ENT Specialist', 'ENT Specialist'), ('Orthologist', 'Orthologist'), ('Opthalmologist', 'Opthalmologist'), ('Dentist', 'Dentist'), ('Cardiologist', 'Cardiologist'), ('Pathologist', 'Pathologist')], max_length=120),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Post',
            field=models.CharField(default='Doctor', max_length=60),
        ),
    ]
